export const data = [
  {
    'School_id': '1',
    ' Section_id': ' Sec-01',
    ' Section_name': ' Section 1',
    ' Name': ' Tango',
    ' Grade': ' A',
    ' Subject': ' Listening',
  },
  {
    'School_id': '1',
    ' Section_id': ' Sec-01',
    ' Section_name': ' Section 1',
    ' Name': ' Tango 1',
    ' Grade': ' A',
    ' Subject': ' Writing',
  },
  {
    'School_id': '2',
    ' Section_id': ' Sec-02',
    ' Section_name': ' Section 2',
    ' Name': ' Charlie',
    ' Grade': ' A',
    ' Subject': ' Listening',
  },
  {
    'School_id': '2',
    ' Section_id': ' Sec-02',
    ' Section_name': ' Section 2',
    ' Name': ' Charlie',
    ' Grade': ' A',
    ' Subject': ' Writing',
  },
  {
    'School_id': '3',
    ' Section_id': ' Sec-03',
    ' Section_name': ' Section 3',
    ' Name': ' Delta',
    ' Grade': ' A',
    ' Subject': ' Listening',
  },
  {
    'School_id': '3',
    ' Section_id': ' Sec-03',
    ' Section_name': ' Section 3',
    ' Name': ' Delta',
    ' Grade': ' A',
    ' Subject': ' Writing',
  },
  {
    'School_id': '4',
    ' Section_id': ' Sec-04',
    ' Section_name': ' Section 4',
    ' Name': ' Victor',
    ' Grade': ' A',
    ' Subject': ' Listening',
  },
  {
    'School_id': '4',
    ' Section_id': ' Sec-04',
    ' Section_name': ' Section 4',
    ' Name': ' Victor',
    ' Grade': ' A',
    ' Subject': ' Writing',
  },
];
